version: "3"

services:
    postgresql:
        image: postgres:latest
        ports:
            - 65432:5432
        environment:
            POSTGRES_USER: uttt
            POSTGRES_PASSWORD: supersecretpassword
        volumes:
            - ./data:/var/lib/postgresql/data
