CREATE TABLE branches (
    state CHAR(30) PRIMARY KEY,
    distance INT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX branches_done_distance_state ON branches (done, distance, state);

CREATE TABLE branches_next (
    current CHAR(30),
    next CHAR(30),
    CONSTRAINT branches_next_pkey PRIMARY KEY (current, next)
);

INSERT INTO branches (state, distance) VALUES ('SAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('AQAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('CEAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('EBAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('GAQAAAAAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('IAEAAAAAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('KABAAAAAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('MAAQAAAAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('OAAEAAAAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('QAABAAAAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('AAAAIAAAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('CAAACAAAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('EAAAAgAAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('GAAAAIAAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('IAAAACAAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('KAAAAAgAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('MAAAAAIAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('OAAAAACAAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('QAAAAAAgAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('AAAAAAAEAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('CAAAAAABAAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('EAAAAAAAQAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('GAAAAAAAEAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('IAAAAAAABAAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('KAAAAAAAAQAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('MAAAAAAAAEAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('OAAAAAAAABAAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('QAAAAAAAAAQAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('AAAAAAAAAACAAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('CAAAAAAAAAAgAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('EAAAAAAAAAAIAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('GAAAAAAAAAACAAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('IAAAAAAAAAAAgAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('KAAAAAAAAAAAIAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('MAAAAAAAAAAACAAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('OAAAAAAAAAAAAgAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('QAAAAAAAAAAAAIAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('AAAAAAAAAAAAABAAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('CAAAAAAAAAAAAAQAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('EAAAAAAAAAAAAAEAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('GAAAAAAAAAAAAABAAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('IAAAAAAAAAAAAAAQAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('KAAAAAAAAAAAAAAEAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('MAAAAAAAAAAAAAABAAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('OAAAAAAAAAAAAAAAQAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('QAAAAAAAAAAAAAAAEAAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('AAAAAAAAAAAAAAAAAgAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('CAAAAAAAAAAAAAAAAIAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('EAAAAAAAAAAAAAAAACAAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('GAAAAAAAAAAAAAAAAAgAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('IAAAAAAAAAAAAAAAAAIAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('KAAAAAAAAAAAAAAAAACAAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('MAAAAAAAAAAAAAAAAAAgAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('OAAAAAAAAAAAAAAAAAAIAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('QAAAAAAAAAAAAAAAAAACAAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('AAAAAAAAAAAAAAAAAAAAQAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('CAAAAAAAAAAAAAAAAAAAEAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('EAAAAAAAAAAAAAAAAAAABAAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('GAAAAAAAAAAAAAAAAAAAAQAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('IAAAAAAAAAAAAAAAAAAAAEAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('KAAAAAAAAAAAAAAAAAAAABAAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('MAAAAAAAAAAAAAAAAAAAAAQAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('OAAAAAAAAAAAAAAAAAAAAAEAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('QAAAAAAAAAAAAAAAAAAAAABAAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('AAAAAAAAAAAAAAAAAAAAAAAIAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('CAAAAAAAAAAAAAAAAAAAAAACAAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('EAAAAAAAAAAAAAAAAAAAAAAAgAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('GAAAAAAAAAAAAAAAAAAAAAAAIAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('IAAAAAAAAAAAAAAAAAAAAAAACAAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('KAAAAAAAAAAAAAAAAAAAAAAAAgAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('MAAAAAAAAAAAAAAAAAAAAAAAAIAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('OAAAAAAAAAAAAAAAAAAAAAAAACAAAA', 0);
INSERT INTO branches (state, distance) VALUES ('QAAAAAAAAAAAAAAAAAAAAAAAAAgAAA', 0);
INSERT INTO branches (state, distance) VALUES ('AAAAAAAAAAAAAAAAAAAAAAAAAAEAAA', 0);
INSERT INTO branches (state, distance) VALUES ('CAAAAAAAAAAAAAAAAAAAAAAAAABAAA', 0);
INSERT INTO branches (state, distance) VALUES ('EAAAAAAAAAAAAAAAAAAAAAAAAAAQAA', 0);
INSERT INTO branches (state, distance) VALUES ('GAAAAAAAAAAAAAAAAAAAAAAAAAAEAA', 0);
INSERT INTO branches (state, distance) VALUES ('IAAAAAAAAAAAAAAAAAAAAAAAAAABAA', 0);
INSERT INTO branches (state, distance) VALUES ('KAAAAAAAAAAAAAAAAAAAAAAAAAAAQA', 0);
INSERT INTO branches (state, distance) VALUES ('MAAAAAAAAAAAAAAAAAAAAAAAAAAAEA', 0);
INSERT INTO branches (state, distance) VALUES ('OAAAAAAAAAAAAAAAAAAAAAAAAAAABA', 0);
INSERT INTO branches (state, distance) VALUES ('QAAAAAAAAAAAAAAAAAAAAAAAAAAAAQ', 0);
